name: Run on Self Hosted Runner

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: sleep 120

  deploy:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: sleep 120

  test:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: sleep 120
